services:
  nextjs:
    build: ./ai-saas
    ports:
      - "3000:3000"
      - "5555:5555" # prisma
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ./ai-saas:/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: